import React, { useMemo, useState } from 'react'
import { useSelector } from 'react-redux'
import Wrapper from '@/components/shared/wraper';
import Form from '@/components/checkout/form';
import OrderSection from '@/components/checkout/orderSection';
import Head from 'next/head';

function Checkout() {
    const { cartItems } = useSelector((state: any) => state.cart);
    const subTotal: number = useMemo(() => {
        let total = 0;
        cartItems.forEach((element: any) => {
            total += (element.quantity*element.oneQuantity)
        });
        return total
    }, [cartItems]);
  return (
    <>
    <Head>
      <title>Checkout</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Wrapper>
      <div className='h-auto items-center flex justify-between md:flex-row flex-col-reverse'>
        <Form/>
        <OrderSection/>

      </div>

    </Wrapper>
    </>
  )
}

export default Checkout